rm(list=ls())
source("R/utilities.R")

OLD_FAC_INFO <- read_fac_info()

changes_df <- bind_rows(
    tibble(Facility.ID=1772, State='Mississippi', Name='ICE ADAMS COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1773, State='California', Name='ADELANTO ICE PROCESSING CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1774, State='Louisiana', Name='ICE ALEXANDRIA STAGING FACILITY', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1775, State='Louisiana', Name='ICE ALLEN PARISH PUBLIC SAFETY COMPLEX', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1776, State='Colorado', Name='ICE DENVER CONTRACT DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1777, State='Florida', Name='ICE BAKER COUNTY SHERIFFS OFFICE', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1778, State='New Jersey', Name='ICE BERGEN COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1779, State='Texas', Name='ICE BLUEBONNET DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='MTC'),
    tibble(Facility.ID=1780, State='Massachusetts', Name='ICE BRISTOL COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1781, State='Florida', Name='ICE BROWARD TRANSITIONAL CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1782, State='New York', Name='ICE BUFFALO BATAVIA SERVICE PROCESSING CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1783, State='Utah', Name='ICE CACHE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1784, State='Michigan', Name='ICE CALHOUN COUNTY CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1785, State='Pennsylvania', Name='ICE CAMBRIA COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1786, State='Virginia', Name='ICE CAROLINE DETENTION FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1787, State='Louisiana', Name='ICE CATAHOULA CORRECTIONAL CENTER', Is.Different.Operator=TRUE, Different.Operator='LaSalle Corrections'),
    tibble(Facility.ID=1788, State='Arizona', Name='ICE CCA FLORENCE CORRECTIONAL CENTER', Is.Different.Operator=NA, Different.Operator=NA),
    tibble(Facility.ID=1789, State='South Carolina', Name='ICE CHARLESTON COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1790, State='Kansas', Name='ICE CHASE COUNTY DETENTION FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1791, State='New Mexico', Name='ICE CIBOLA COUNTY CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1792, State='Indiana', Name='ICE CLAY COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1793, State='Texas', Name='ICE COASTAL BEND DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1794, State='South Carolina', Name='ICE COLUMBIA REGIONAL CARE CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1795, State='Maine', Name='ICE CUMBERLAND COUNTY JAIL', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1796, State='Nebraska', Name='ICE DOUGLAS COUNTY', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1797, State='Texas', Name='ICE EDEN DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1798, State='Texas', Name='ICE EL PASO SERVICE PROCESSING CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1799, State='Texas', Name='ICE EL VALLE DETENTION FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1800, State='New Jersey', Name='ICE ELIZABETH CONTRACT DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1801, State='Arizona', Name='ICE ELOY FEDERAL CONTRACT FACILITY', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1802, State='New Jersey', Name='ICE ESSEX COUNTY CORRECTIONAL FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1803, State='Alabama', Name='ICE ETOWAH COUNTY JAIL ALABAMA', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1804, State='Virginia', Name='ICE IMMIGRATION CENTERS OF AMERICA FARMVILLE', Is.Different.Operator=TRUE, Different.Operator=NA),
    tibble(Facility.ID=1805, State='Arizona', Name='ICE FLORENCE SERVICE PROCESSING CENTER', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1806, State='Georgia', Name='FOLKSTON ICE PROCESSING CENTER D RAY JAMES', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1807, State='Massachusetts', Name='ICE FRANKLIN COUNTY HOUSE OF CORRECTION', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1808, State='Minnesota', Name='ICE FREEBORN COUNTY ADULT DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1809, State='Ohio', Name='ICE GEAUGA COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1810, State='Florida', Name='ICE GLADES COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1811, State='California', Name='ICE GOLDEN STATE ANNEX FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1812, State='Mississippi', Name='ICE HANCOCK COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1813, State='Nevada', Name='ICE HENDERSON DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1814, State='Texas', Name='ICE HOUSTON CONTRACT DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1815, State='New Jersey', Name='ICE HUDSON COUNTY CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1816, State='Texas', Name='ICE POLK COUNTY ADULT DETENTION FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1817, State='California', Name='ICE IMPERIAL REGIONAL DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='MTC'),
    tibble(Facility.ID=1818, State='Georgia', Name='ICE IRWIN COUNTY DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='LaSalle Corrections'),
    tibble(Facility.ID=1819, State='Louisiana', Name='ICE JACKSON PARISH CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1820, State='Texas', Name='ICE JOE CORLEY DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1821, State='Texas', Name='ICE JOHNSON COUNTY CORRECTIONS CENTER', Is.Different.Operator=TRUE, Different.Operator='LaSalle Corrections'),
    tibble(Facility.ID=1822, State='Texas', Name='ICE KARNES COUNTY RESIDENTIAL CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1823, State='Oklahoma', Name='ICE KAY COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1824, State='Florida', Name='ICE KROME NORTH SERVICE PROCESSING CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1825, State='Arizona', Name='ICE LA PALMA CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1826, State='California', Name='ICE LA STAGING', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1827, State='Texas', Name='ICE LAREDO PROCESSING CENTER', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1828, State='Florida', Name='ICE LARKIN BEHAVIORAL HEALTH CENTER', Is.Different.Operator=TRUE, Different.Operator=NA),
    tibble(Facility.ID=1829, State='Louisiana', Name='ICE LASALLE CORR CTR OLLA', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1830, State='Louisiana', Name='ICE JENALASALLE DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1831, State='Texas', Name='ICE LIMESTONE COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1832, State='Missouri', Name='ICE LINCOLN COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1833, State='Iowa', Name='ICE LINN COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1834, State='Florida', Name='ICE LOCAL HOSPITAL MIAMI FL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1835, State='Illinois', Name='ICE MCHENRY COUNTY CORRECTIONAL FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1836, State='California', Name='ICE MESA VERDE DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1837, State='Michigan', Name='ICE MONROE COUNTY DETENTION-DORM', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1838, State='Missouri', Name='ICE MONTGOMERY COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1839, State='Texas', Name='ICE MONTGOMERY PROCESSING CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1840, State='Oklahoma', Name='ICE OKMULGEE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1841, State='Missouri', Name='ICE MORGAN COUNTY ADULT DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1842, State='Ohio', Name='ICE MORROW COUNTY CORRECTIONAL FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1843, State='Nevada', Name='ICE NEVADA SOUTHERN DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1844, State='Washington', Name='ICE NORTHWEST DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1845, State='Nevada', Name='ICE NYE COUNTY DETENTION CENTER SOUTHERN PAHRUMP', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1846, State='California', Name='ICE OTAY MESA DETENTION CENTER SAN DIEGO CDF', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1847, State='New Mexico', Name='ICE OTERO COUNTY PROCESSING CENTER', Is.Different.Operator=TRUE, Different.Operator='MTC'),
    tibble(Facility.ID=1848, State='Nebraska', Name='ICE PHELPS COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1849, State='Pennsylvania', Name='ICE PIKE COUNTY CORRECTIONAL FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1850, State='Louisiana', Name='ICE PINE PRAIRIE CORRECTIONAL CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1851, State='Iowa', Name='ICE POLK COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1852, State='Texas', Name='ICE PORT ISABEL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1853, State='Texas', Name='ICE PRAIRIELAND DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='LaSalle Corrections'),
    tibble(Facility.ID=1854, State='Illinois', Name='ICE PULASKI COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1855, State='Louisiana', Name='ICE RICHWOOD CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1856, State='Texas', Name='ICE RIO GRANDE DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1857, State='Louisiana', Name='ICE CONCORDIA PARISH C C', Is.Different.Operator=NA, Different.Operator=NA),
    tibble(Facility.ID=1858, State='Georgia', Name='ICE ROBERT A DEYTON DETENTION FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1859, State='Texas', Name='ICE ROLLING PLAINS DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='LaSalle Corrections'),
    tibble(Facility.ID=1860, State='Michigan', Name='ICE SAINT CLAIR COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1861, State='Puerto Rico', Name='ICE SAN JUAN STAGING FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1862, State='Arizona', Name='ICE SAN LUIS REGIONAL DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='LaSalle Corrections'),
    tibble(Facility.ID=1863, State='Minnesota', Name='ICE SHERBURNE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1864, State='Louisiana', Name='ICE SOUTH LOUISIANA DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1865, State='Texas', Name='ICE SOUTH TEXAS FAMILY RESIDENTIAL CENTER', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1866, State='Texas', Name='ICE SOUTH TEXAS DETENTION COMPLEX', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1867, State='Georgia', Name='ICE STEWART DETENTION CENTER', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1868, State='New Hampshire', Name='ICE STRAFFORD COUNTY CORRECTIONS', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1869, State='Texas', Name='ICE HUTTO CCA', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1870, State='New Mexico', Name='ICE TORRANCE COUNTY DETENTION FACILITY', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1871, State='Florida', Name='ICE WAKULLA COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1872, State='Utah', Name='ICE WASHINGTON COUNTY JAIL PURGATORY CORRECTIONAL FAC', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1873, State='Texas', Name='ICE WEBB COUNTY DETENTION CENTER CCA', Is.Different.Operator=TRUE, Different.Operator='CoreCivic'),
    tibble(Facility.ID=1874, State='Louisiana', Name='ICE WINN CORRECTIONAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1875, State='Maryland', Name='ICE WORCESTER COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1876, State='Rhode Island', Name='ICE WYATT DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1877, State='Pennsylvania', Name='ICE YORK COUNTY PRISON', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1878, State='Not Available', Name='ALL ICE FACILITIES', Is.Different.Operator=NA, Different.Operator=NA),
    tibble(Facility.ID=1978, State='Pennsylvania', Name='ICE BERKS FAMILY RESIDENTIAL CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1979, State='Ohio', Name='ICE BUTLER COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1980, State='Pennsylvania', Name='ICE CLINTON COUNTY CORRECTIONAL FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1981, State='Wisconsin', Name='ICE DODGE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1982, State='Iowa', Name='ICE HARDIN COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1983, State='Maryland', Name='ICE HOWARD COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1984, State='Minnesota', Name='ICE KANDIYOH COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1985, State='Texas', Name='ICE LASALLE COUNTY REGIONAL DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1986, State='Minnesota', Name='ICE NOBLES COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1987, State='New York', Name='ICE ORANGE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1988, State='Massachusetts', Name='ICE PLYMOUTH COUNTY CORRECTIONAL FACILITY', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1989, State='Ohio', Name='ICE SENECA COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1990, State='West Virginia', Name='ICE SOUTH CENTRAL REGIONAL JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1991, State='California', Name='ICE YUBA COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1992, State='Delaware', Name='ICE HOWARD R YOUNG CORRECTIONAL INSTITUTION', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1993, State='Illinois', Name='ICE KANKAKEE COUNTY DETENTION CENTER', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=1994, State='Texas', Name='ICE KARNES COUNTY CORRECTIONAL CENTER', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=1995, State='Nebraska', Name='ICE HALL COUNTY SHERIFF', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=2179, State='Iowa', Name='ICE POTTAWATTAMIE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=2180, State='Michigan', Name='ICE MONROE COUNTY DETENTION', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=2181, State='Texas', Name='ICE EL PASO COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=2325, State='Pennsylvania', Name='ICE YORK COUNTY JAIL', Is.Different.Operator=NA, Different.Operator=NA),
    tibble(Facility.ID=2326, State='Texas', Name='ICE BEST WESTERN HOTEL - EL PASO', Is.Different.Operator=TRUE, Different.Operator='Endeavors'),
    tibble(Facility.ID=2327, State='Texas', Name='ICE COMFORT SUITES - EL PASO', Is.Different.Operator=TRUE, Different.Operator='Endeavors'),
    tibble(Facility.ID=2328, State='Arizona', Name='ICE HOLIDAY INN - CHANDLER', Is.Different.Operator=TRUE, Different.Operator='Endeavors'),
    tibble(Facility.ID=2329, State='Kentucky', Name='ICE BOONE COUNTY JAIL', Is.Different.Operator=FALSE, Different.Operator=NA),
    tibble(Facility.ID=2457, State='Georgia', Name='ICE FOLKSTON ANNEX IHSC', Is.Different.Operator=TRUE, Different.Operator='GeoGroup'),
    tibble(Facility.ID=2458, State='Texas', Name='ICE LA QUINTA - PEARSALL HOUSE OF PEACE', Is.Different.Operator=TRUE, Different.Operator='Endeavors'))

updated_fac_info <- rows_update(
    OLD_FAC_INFO, changes_df, by = c("Facility.ID", "State", "Name"))

write.csv(updated_fac_info, "data/fac_data.csv", row.names = FALSE, na = "")
